version: '3.1'

services:
  app:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: https://vm.ui-app.org/phpmyadmin/index.php
      WORDPRESS_DB_USER: dbo
      WORDPRESS_DB_PASSWORD: db./2024
      WORDPRESS_DB_NAME: dbo
    volumes:
      - ../..:/workspaces:cached

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampleuser
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
