version: '3.1'

services:
  app:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD:
      WORDPRESS_DB_NAME: ui-app
    volumes:
      - ../..:/workspaces:cached

  db:
    image: mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ui-app
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
